import {
  LogoMobile,
  Logo,
  glow,
  bucket,
  LogoB,
  casablanca,
  scooter,
  basket,
  bucketMobile,
  YokoEat_low,
  YOKOMarket_low,
  Tagine_low,
  Delivery_low,
  Traditional_low,
  YOKO_EAT_low,
  YOKO_Rest_low,
  Rue_low,
  Bike_low,
  cerave,
  cerave_logo,
  philips,
  vectorObj,
  airfryer,
} from "./images.js";

const ImageConfig = [
  { uri: Logo },
  { uri: glow },
  { uri: cerave },
  { uri: cerave_logo },
  { uri: philips },
  { uri: airfryer },

  { uri: bucket },
  { uri: LogoB },
  { uri: casablanca },
  { uri: scooter },
  { uri: basket },
  { uri: bucketMobile },
  { uri: YokoEat_low },
  { uri: YOKOMarket_low },
  { uri: Tagine_low },
  { uri: Delivery_low },
  { uri: Traditional_low },
  { uri: Rue_low },
  { uri: vectorObj },

  { uri: YOKO_EAT_low },
  { uri: YOKO_Rest_low },
  { uri: Bike_low },

  // { uri: Traditional },
];

export default ImageConfig;
